/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  // tutorialSidebar1: [
  //   {
  //     type: 'doc',
  //     label: 'Intro',
  //     id: 'intro',
  //   },
  //   {
  //     type: 'category',
  //     label: 'Guide',
  //     items: ['guide/verifyDID','guide/updatecatinfo','guide/verifyDID-ZH','guide/updatecatinfo-ZH'],
  //     collapsible: true,
  //     collapsed: false,
  //   },
  //   {
  //     type: 'link',
  //     label: 'Twitter', // The link label
  //     href: 'https://twitter.com/spacescan_io', // The external URL
      
  //   },
  //   {
  //     type: 'link',
  //     label: 'Discord', // The link label
  //     href: 'https://discord.gg/Bb4sj3Bg9P', // The external URL
      
  //   },
  // ],
   
};

module.exports = sidebars;
